onlineskaut/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls")),
]

website/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib import admin

from . import views
from .views import SignUpView, ForumView

urlpatterns = [
    url("^$", views.index, name="index"),
    url("accounts/profile", views.ProfileView.as_view(), name="profile"),
    url("accounts/challenges", views.ChallengesView.as_view(), name="challenges"),
    url("accounts/forum", ForumView.as_view(), name="forum"),
    # Django Auth
    path("accounts/login", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login",),
    path("accounts/logout", auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/signup', SignUpView.as_view(), name='signup'),
]

website/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey("UserProfile", on_delete=models.CASCADE, related_name="post")
    post = models.TextField(help_text='Napiš něco...')
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.post
    
    class Meta:
        ordering = ['-date']

class UserProfile(models.Model):
    nickname = models.CharField(max_length=50, blank=True, null=True, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    bio = models.TextField(blank=True, null=True,default="Tady můžeš napsat něco o sobě...")

    def __str__(self):
        return self.nickname

class Solving(models.Model):
    solved_by = models.ForeignKey("UserProfile", on_delete=models.CASCADE, related_name="solved_by")
    challenge = models.ForeignKey("Challenge", on_delete=models.CASCADE, related_name="challenge")
    date = models.DateTimeField(default=timezone.now)
    is_solved = models.BooleanField(default=False)
    answer = models.TextField(blank=True, null=True)
    
    def __str__(self):
        if self.is_solved:
            solved = "Vyhodnoceno"
        else:
            solved = "Nevyhodnoceno"
        return solved+' - '+self.solved_by.nickname+' - '+self.challenge.name

    class Meta:
        ordering = ['is_solved','-date']

class Challenge(models.Model):
    author = models.ForeignKey("UserProfile", on_delete=models.CASCADE, related_name="author", default=1)
    name = models.CharField(max_length=60,unique=True)
    text = models.TextField()
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="category")

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=60,help_text="blue/red/green")
    
    def __str__(self):
        return self.name

website/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Post, UserProfile, Solving


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password1"]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('post',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('nickname','bio',)

class SolvingForm(forms.ModelForm):
    challenge = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = Solving
        fields = ('answer',)

website/views.py
from django.shortcuts import render, redirect  
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .models import Post, Challenge, Category, Solving, UserProfile
from django.contrib.auth.models import User
from .forms import RegisterForm, PostForm, UserProfileForm, SolvingForm
import datetime, math

from django import template
register = template.Library()


def index(request: HttpRequest) -> HttpResponse:
    return render(request, '../website/index.html', {})

class SignUpView(generic.CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html" 

    def get(self, request, *args, **kwargs):
        username = None
        if request.user.is_authenticated:
            username = request.user.profile
        challenges = Solving.objects.filter(solved_by=username).order_by('challenge__category__name', '-is_solved','challenge__id')
        category_list = Category.objects.all()
        znalosti_img='images/avatar/zn_'+str(Solving.objects.filter(is_solved=True,solved_by=username,challenge__category__name="Znalosti").count())+'.png'
        schopnosti_img='images/avatar/sc_'+str(Solving.objects.filter(is_solved=True,solved_by=username,challenge__category__name="Schopnosti").count())+'.png'
        pratelstvi_img='images/avatar/pr_'+str(Solving.objects.filter(is_solved=True,solved_by=username,challenge__category__name="Přátelství").count())+'.png'
        my_record = UserProfile.objects.get(user=request.user)
        form = UserProfileForm(instance=my_record)
        context = {
            'challenges': challenges,
            'category_list': category_list,
            'pratelstvi_img':pratelstvi_img,
            'schopnosti_img':schopnosti_img,
            'znalosti_img':znalosti_img,
            'form':form
        }
        return render(request, self.template_name, context)
    
    def post(self, request):
        profil = UserProfile.objects.get(user=request.user)
        form = UserProfileForm(request.POST, instance=profil)
        if form.is_valid():
            profil.save()

            bio = form.cleaned_data['bio']
            return redirect(self.template_name)
        
        args = {'form':form,'bio':bio}
        return render(request, self.template_name, args)

class ChallengesView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/challenges.html"

    def get(self, request, *args, **kwargs):
        
        form = SolvingForm()
        if request.user.is_authenticated:
            username = request.user.profile
        time = datetime.datetime.now()
        week = int(time.strftime("%V"))
        challenge_list = Challenge.objects.none()
        category_list = Category.objects.all()
        solved_list = Solving.objects.filter(is_solved=True,solved_by=username)
        i = 0
        while i < Category.objects.all().count():
            in_category = Challenge.objects.filter(category=category_list[i].id)
            in_category_count = Challenge.objects.filter(category=category_list[i].id).count()
            challenge = int((week / in_category_count - math.floor(week / in_category_count))*in_category_count)
            challenge_id = in_category[challenge].id
            challenge_list |= Challenge.objects.filter(id=challenge_id)
            i = i + 1
        context = {
            'challenge_list':challenge_list,
            'category_list':category_list,
            'solved_list':solved_list,
            'form':form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = SolvingForm(request.POST)
        if form.is_valid():

            solving = form.save(commit=False)
            solving.solved_by = request.user.profile
            solving.challenge = Challenge.objects.get(pk=form.cleaned_data['challenge'])
            solving.save()

            return redirect(self.template_name)
        
        args = {'form':form}
        return render(request, self.template_name, args)

class ForumView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/forum.html" 

    def get(self, request, *args, **kwargs):
        form = PostForm()
        posts = Post.objects.all()
        context = {
            'post_list': posts,
            'form':form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user.profile
            post.save()

            text = form.cleaned_data['post']
            form = PostForm()
            return redirect(self.template_name)
        
        args = {'form':form,'text':text}
        return render(request, self.template_name, args)

website/templates/website/accounts/challenges.html
{% extends 'base.html' %}

{% block title %}Výzvy{% endblock %}

{% block content %}
{% with profile=user.profile%}
<section class="masthead page-section text-secondary mb-0" id="about">
    <div class="container">
        <!-- About Section Heading-->
        <div class="text-center">
            <h2 class="page-section-heading d-inline-block text-secondary">Výzvy</h2>
        </div>
        <!-- Icon Divider-->
        <div class="divider-custom divider-secondary">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="far fa-grin-stars"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row">
        {% for challenge in challenge_list %}
            <div class="col-lg-3 vyzva_list">
                <div class="rounded bg-primary text-light vyzva">
                    <h3 class="pre-wrap lead nazev_vyzvy">{{ challenge.name }}</h3>
                    {% for category in category_list %}
                        {% if challenge.category|stringformat:"s" == category.name %}
                            <div class="divider-custom divider-{{ category.color }}">
                                <div class="divider-custom-line"></div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <p class="pre-wrap lead">{{ challenge.text }}</p>
                    <p><button type="button" class="btn btn-secondary resit" data-id="{{ challenge.id }}">Vyřešit</button></p>
                    {% for solved in solved_list %}
                        {% if solved.challenge|stringformat:"s" == challenge.name %}
                            <i class="far fa-fw fa-check-circle splneno"></i>
                            <p>{{solved.date}}</p>
                        {% endif %}
                    {% endfor %}
                    
                </div>
            </div>
        {% endfor %}
        </div>
        <div class="col-lg-8 rounded bg-primary text-light challenges-form">
            <form method="POST" id="vyzva_form">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-outline-light btn-social mx-1" type="submit"><i class="fas fa-fw fa-comment"></i></button>
            </form>
        </div>
    </div>
</section>
{% endwith %}
{% endblock %}

{% block script %}
    <script>
        $(function(){
            $('#vyzva_form').hide();
            $('button.resit').on('click', function() {
                $('#id_challenge').val($(this).data('id'));
                $('#vyzva_form').show();
            });
        });
    </script>
{% endblock %}

website/templates/website/accounts/forum.html
{% extends 'base.html' %}

{% block title %}Fórum{% endblock %}

{% block content %}
<section class="masthead page-section text-secondary mb-0" id="about">
    <div class="container">
        <!-- About Section Heading-->
        <div class="text-center">
            <h2 class="page-section-heading d-inline-block text-secondary">Fórum</h2>
        </div>
        <!-- Icon Divider-->
        <div class="divider-custom divider-secondary">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="far fa-grin-stars"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row post_list">
            {% with profile=user.profile%}
            {% if profile %}
                <div class="col-lg-8 rounded bg-primary text-light post">
                    <form method="POST" class="forum-form">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn btn-outline-light btn-social mx-1" type="submit"><i class="fas fa-fw fa-comment"></i></button>
                    </form>
                </div>
            {% endif %}
            {% endwith %}
        </div>
        {% for post in post_list %}
        <div class="row post_list">
            <div class="col-lg-8 rounded bg-primary text-light post">
                <p class="pre-wrap lead autor">{{ post.author }}</p>
                {{ post.date }}
                <p class="pre-wrap lead">{{ post.post }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

website/templates/website/accounts/login.html
{% extends 'base.html' %}

{% block title %}Přihlášení{% endblock %}

{% block content %}
<section class="masthead page-section bg-primary text-white mb-0" id="about">
    <div class="container">
        <!-- About Section Heading-->
        <div class="text-center">
            <h2 class="page-section-heading d-inline-block">Přihlášení</h2>
        </div>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="far fa-grin-stars"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row">
            <div class="col-lg-8 ml-auto">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Přihlásit</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

website/templates/website/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}

{% block title %}Profil{% endblock %}

{% block content %}
{% with profile=user.profile%}
<section class="masthead page-section text-secondary mb-0">
    <div class="container">
        <!-- About Section Heading-->
        <div class="text-center">
            {% if profile %}
            <h2 class="page-section-heading d-inline-block text-secondary">{{profile.nickname|default:""}}</h2>
            {% else %}
            <h2 class="page-section-heading d-inline-block text-secondary">{{user.username}}</h2>
            {% endif %}
        </div>
        <!-- Icon Divider-->
        <div class="divider-custom divider-secondary">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="far fa-grin-stars"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row profile_list">
            <div class="col-lg-6 ml-auto .profile_block">
                <div class="rounded bg-primary text-light avatar">
                    <div class="parent center">
                        <img src="{% static pratelstvi_img %}" class="background img-fluid img-responsive center" alt="spolecnik">
                        <img src="{% static schopnosti_img %}" class="foreground img-fluid img-responsive center" alt="zbran">
                        <img src="{% static znalosti_img %}" class="foreground img-fluid img-responsive center" alt="pokryvka">
                    </div>                    
                </div>
                <div class="rounded bg-primary text-light avatar">
                    <!-- Zjednodušení kódu-->
                    {% for category in category_list %}
                    <div>
                        <h4>{{category.name}}</h4>
                        <div class="divider-custom divider-{{ category.color }} divider-profil">
                            <div class="divider-custom-line"></div>
                        </div>
                        {% for challenge in challenges %}
                            {% if challenge.challenge.category|stringformat:"s" == category.name %}
                                {% if challenge.is_solved %}
                                    <span class="text-{{ category.color }} solved-dot">&#x25cf;</span>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-6 mr-auto .profile_block">
                <div class="rounded bg-primary text-light bio">
                    <h4 class="border-bottom">Můj popis</h4>
                    {% if profile.bio %}
                        <p class="pre-wrap lead">{{ profile.bio|default:""}}</p>
                    {% else %}
                        <p class="pre-wrap lead"> Napiš si tu něco...</p>
                    {% endif %}
                    <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal0">
                        <div class="portfolio-item-caption-content btn-outline-light btn-social btn"><i class="fas fa-fw fa-edit"></i></div>
                    </div>
                    <div class="portfolio-modal modal fade" id="portfolioModal0" tabindex="-1" role="dialog" aria-labelledby="#portfolioModal0Label" aria-hidden="true">
                        <div class="modal-dialog modal-xl" role="document">
                            <div class="modal-content">
                                <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="fas fa-times"></i></span></button>
                                <div class="modal-body text-center">
                                    <div class="container">
                                        <div class="row justify-content-center">
                                            <div class="col-lg-8">
                                                <!-- Portfolio Modal - Title-->
                                                <h2 class="portfolio-modal-title text-secondary mb-0">Můj profil</h2>
                                                <!-- Icon Divider-->
                                                <div class="divider-custom">
                                                    <div class="divider-custom-line"></div>
                                                    <div class="divider-custom-icon"><i class="far fa-grin-stars"></i></div>
                                                    <div class="divider-custom-line"></div>
                                                </div>
                                                <form action="" method="post" class="profile-form">
                                                    {% csrf_token %}
                                                    {{ form }}
                                                    <button class="btn btn-danger" href="#" data-dismiss="modal"><i class="fas fa-times fa-fw"></i>Zrušit</button>
                                                    <button class="btn btn-success" type="submit"><i class="fas fa-fw fa-edit"></i>Upravit</button>
                                                <form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
    </div>
</section>
{% endwith %}
{% endblock %}

website/templates/website/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Registrace{% endblock %}

{% block content %}
<section class="masthead page-section bg-primary text-white mb-0" id="about">
    <div class="container">
        <!-- About Section Heading-->
        <div class="text-center">
            <h2 class="page-section-heading d-inline-block">Registrace</h2>
        </div>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="far fa-grin-stars"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row">
            <div class="col-lg-8 ml-auto">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Registrovat</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}